# Generated by Django 4.0.6 on 2022-07-24 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0008_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='user',
        ),
    ]
